# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(321, 407)
        Dialog.setMinimumSize(QtCore.QSize(321, 407))
        Dialog.setMaximumSize(QtCore.QSize(321, 407))
        self.table_device = QtWidgets.QTableWidget(Dialog)
        self.table_device.setGeometry(QtCore.QRect(10, 10, 301, 271))
        self.table_device.setObjectName("table_device")
        self.table_device.setColumnCount(2)
        self.table_device.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_device.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_device.setHorizontalHeaderItem(1, item)
        self.btn_start = QtWidgets.QPushButton(Dialog)
        self.btn_start.setGeometry(QtCore.QRect(160, 350, 151, 51))
        self.btn_start.setObjectName("btn_start")
        self.btn_refresh = QtWidgets.QPushButton(Dialog)
        self.btn_refresh.setGeometry(QtCore.QRect(10, 350, 141, 51))
        self.btn_refresh.setObjectName("btn_refresh")
        self.horizontalSlider = QtWidgets.QSlider(Dialog)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 310, 301, 22))
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(10)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setProperty("value", 1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider.setTickInterval(1)
        self.horizontalSlider.setObjectName("horizontalSlider")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.table_device.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "DeviceName"))
        item = self.table_device.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "SwipeNumber"))
        self.btn_start.setText(_translate("Dialog", "Start"))
        self.btn_refresh.setText(_translate("Dialog", "Refresh"))
